name: CD for Latest Versions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  push-latest-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true  

      - name: Pull LFS objects
        run: git lfs pull  

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Hugging Face Hub
        run: |
          python -m pip install --upgrade pip
          pip install huggingface-hub

      - name: Determine Latest Model Version
        id: get-latest-version
        run: |
          LATEST_MODEL=$(ls models | grep -E '^model_[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          echo "Latest model directory: $LATEST_MODEL"
          echo "latest_model=$LATEST_MODEL" >> $GITHUB_ENV
      
      - name: Copy and Rename Model File
        run: |
          cp "models/${{ env.latest_model }}/${{ env.latest_model }}.pth" "trashnet.pth"
          cp "models/${{ env.latest_model }}/config.json" "config.json"
          cp "models/${{ env.latest_model }}/metrics.json" "metrics.json"
          cp "models/${{ env.latest_model }}/README.md" "README.md"
  
      - name: Upload Latest Model
        run: |
          echo "Uploading the latest model to root..."
          huggingface-cli upload \
            --repo-type=model \
            --commit-message "feat: Update main with the latest model" \
            ${{ secrets.HF_REPO_NAME }} "trashnet.pth" "config.json" "metrics.json" "README.md"