name: CD for Latest Versions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  push-latest-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Uncomment if use LFS
      #   with:
      #     lfs: true  

      # - name: Pull LFS objects
      #   run: git lfs pull  

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
        # Install dependencies using nektos/act (If want to use local dependencies)
      - name: Install dependencies using nektos/act
        run: |
          python -m pip install --no-index --find-links=.cache/cd/pip huggingface-hub
      
      # Install dependencies (Uncomment if want to install dependencies from PyPI and comment above)
      # - name: Install Hugging Face Hub
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install huggingface-hub

      - name: Determine Latest Model Version
        id: get-latest-version
        run: |
          LATEST_MODEL=$(ls models | grep -E '^model_[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          echo "Latest model directory: $LATEST_MODEL"
          echo "latest_model=$LATEST_MODEL" >> $GITHUB_ENV
      
      - name: Copy and Rename Model File
        run: |
          mkdir -p "models/latest"
          cp "models/${{ env.latest_model }}/${{ env.latest_model }}.keras" "models/latest/trashnet.keras"
          cp "models/${{ env.latest_model }}/config.json" "models/latest/config.json"
          cp "models/${{ env.latest_model }}/metrics.json" "models/latest/metrics.json"
          cp "models/${{ env.latest_model }}/README.md" "models/latest/README.md"
  
      - name: Upload Latest Model
        run: |
          echo "Uploading the latest model to root..."
          huggingface-cli upload \
            ${{ secrets.HF_REPO_NAME }} models/latest \
            --repo-type=model \
            --commit-message "feat: Update main with the latest model" \
            --token ${{ secrets.HF_TOKEN }}
