name: CD for Tagged Versions

on:
  push:
    tags:
      - 'v*'

jobs:
  push-tagged-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true  

      - name: Pull LFS objects
        run: git lfs pull  

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Hugging Face Hub
        run: |
          python -m pip install --upgrade pip
          pip install huggingface-hub

      - name: Login to Huggingface
        run: huggingface-cli login --token ${{ secrets.HF_TOKEN }}

      - name: Extract Tag Version
        id: extract-version
        run: |
          TAG=$(basename "$GITHUB_REF")
          VERSION=${TAG#v}
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Upload Tagged Model
        run: |
          echo "Uploading model version ${{ env.version }} to a new branch..."
          huggingface-cli upload \
            --repo-type=model \
            --commit-message "feat: Release version ${{ env.version }}" \
            --branch "v${{ env.version }}" \
            --token ${{ secrets.HF_TOKEN }} \
            ${{ secrets.HF_REPO_NAME }} "models/model_${{ env.version }}"
