name: CD to Huggingface and WandB
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Run tests
              run: |
                  pytest
            - name: Upload to Huggingface
              uses: huggingface/upload-action@v3
              with:
                  model_id: "your-model-id"
                  model_filename: "model.bin"
                  model_config: "config.json"
                  model_readme: "README.md"
                  # api_token: ${{ secrets.HUGGINGFACE_TOKEN }}
            - name: Upload to WandB
              uses: actions/upload-artifact@v2
              with:
                  name: model