name: CD to Hugging Face

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  push-to-huggingface:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true  

      - name: Pull LFS objects
        run: git lfs pull  

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Hugging Face Hub
        run: |
          python -m pip install --upgrade pip
          pip install huggingface-hub

      - name: Login to Huggingface
        run: |
          huggingface-cli login --token ${{ secrets.HF_TOKEN }}

      - name: Determine Trigger
        id: determine-trigger
        run: |
          if [[ "$GITHUB_REF" == refs/heads/main ]]; then
            echo "trigger=main" >> $GITHUB_ENV
          elif [[ "$GITHUB_REF" == refs/tags/v* ]]; then
            TAG=$(basename "$GITHUB_REF")
            echo "trigger=tag" >> $GITHUB_ENV
            echo "version=${TAG#v}" >> $GITHUB_ENV
          fi

      - name: Upload Model to Hugging Face
        run: |
          echo "Trigger: ${{ env.trigger }}"
          if [[ "${{ env.trigger }}" == "main" ]]; then
            echo "Uploading the latest model to the 'main' branch..."
            huggingface-cli upload \
              --repo-type=model \
              --commit-message "feat: Update main with the latest model" \
              --branch main \
              --token ${{ secrets.HF_TOKEN }} \
              ${{ secrets.HF_REPO_NAME }} "models/latest_model"
          elif [[ "${{ env.trigger }}" == "tag" ]]; then
            echo "Uploading model version ${{ env.version }} to a new branch..."
            huggingface-cli upload \
              --repo-type=model \
              --commit-message "feat: Release version ${{ env.version }}" \
              --branch "v${{ env.version }}" \
              --token ${{ secrets.HF_TOKEN }} \
              ${{ secrets.HF_REPO_NAME }} "models/model_${{ env.version }}"
          else
            echo "Unknown trigger. Exiting."
            exit 1
          fi
