name: CI Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  unit-and-integration-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      #   with:
      #     lfs: true  

      # - name: Pull LFS objects
      #   run: git lfs pull  

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install dependencies (If want to use local dependencies)
      - name: Install dependencies using nektos/act
        run: |
          python -m pip install --no-index --find-links=.cache/ci/pip tensorflow numpy pillow
        
      # Uncomment if want to install dependencies from PyPI and comment above
      # - name: Install dependencies
      #   run: |
        # python -m pip install --upgrade pip
        # pip install tensorflow numpy

      # Run Integration Tests
      - name: Run Integration Tests
        run: |
          echo "Running Integration Tests..."
          python test/integration_test.py
